analytics: {}
color:
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#787878'
    - '#000000'
    - '#000000'
  brandStrength: 0.295045
  lightness: 0.823198
  rhythmicContrast: 0.273648
  saturation: 0.658783
cta: {}
layout_spectrum: 1
name: ThierryDeVynck
opengraph: {}
purpose: {}
typography_spectrum: 0.378378
